export const API_ROOM_VIEW_ALL="http://localhost:4000/room/view-all"
export const API_ROOM_CREATE= "http://localhost:4000/room/add/"
export const API_USER_LOGIN = "http://localhost:4000/user/login";
export const API_USER_SIGNUP = "http://localhost:4000/user/register";
export const API_GET_ALL_USERS = "http://localhost:4000/user/get-all-users"
export const API_ROOM_VIEW_BY_ID = "http://localhost:4000/room/view-by-id";
export const API_MESSAGES_IN_ROOM = "http://localhost:4000/message/view-all/";
export const API_DELETE_USER = "http://localhost:4000/user/delete/"
export const API_UPDATE_USER = "http://localhost:4000/user/update/"
export const API_GET_USER_BY_ID = "http://localhost:4000/user/get-user-by-id/"
